### ISSUE TITLE
can this approach work with private repos?

### ISSUE THREAD

**Issue by surazregmi** [jualoppaz/single-spa-login-example-with-npm-packages#2]
I am working on a project  where i have to integrate three different projects into one. Also i want that other projects will run independently so that we don't have to do double task to update the changes.I find this approach good for me..but we cannot make our project public. Is it possible to make private repos to work with this approach?

**Comment by jualoppaz** [comment]
Hi @surazregmi ! Yes, this approach works fine with private repos also.

You have several options:

- use your private github repo as dependency in your package.json
- use a private package from NPM registry
- deploy your own npm registry like [Verdaccio](https://verdaccio.org/) and publish your private package there

Last option is which I use in other team project and works very well.

Hope this be useful.
