### ISSUE TITLE
Reload gives Page not found after build

### ISSUE THREAD

**Issue by ajaykumarsana** [jualoppaz/single-spa-login-example-with-npm-packages#8]
Hi @jualoppaz,

I cloned [this](https://github.com/jualoppaz/single-spa-login-example-with-npm-packages) repository and ran`npm run build` .
later ran `http-server` to see the build version.
initially it redirected to login , when i reload it gives me error **page can’t be found**

Please help!!

**Comment by jualoppaz** [comment]
Hi @ajaykumarsana !

I suppose that you are running the application in a different way that the README says.

Take a look to this lines in **server.js** file:

https://github.com/jualoppaz/single-spa-login-example-with-npm-packages/blob/1faaf5e775b9eba923764d4df5fad2baaa714910/server.js#L11-L13

This route is very important for avoid the error you mention. For any server route you must serve the index.html file, and let to your frontend app route the application depending on the browser route.

If you use another node script for setup the application you must add some configuration like this :)
